### ISSUE TITLE
Change email authentication

### ISSUE THREAD

**Issue by dkoodev** [wyteboad/howsdish#4]
voteprocess.php 에서
@naver.com 인증에서 
(string)@chadwickschool.org // 선생님 email 인경우에는 숫자가 아니고 이름입니다
(string)2016@chadwickschool.org //12 학년
(string)2017@chadwickschool.org //11 학년
(string)2018@chadwickschool.org //10 학년
(string)2019@chadwickschool.org //9 학년 
로 바꿔야됩니당~

**Comment by jason-wytist** [comment]
Give that a try !

**Comment by jason-wytist** [comment]
You might use regular expression or more complex functions.

But easy implementation is to reject emails including postfixes, from "2020@chadwickschool.org" to "2027@chadwickschool.org".
